language: csharp
solution: Sample.Test.sln
notifications:
email:
recipients:
- khanhduyluu@gmail.com
on_success: [always|never|change] # default: change
on_failure: [always|never|change] # default: always	
install:
  - nuget restore Sample.Test.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Sample.Test.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Sample.Test/bin/Release/Sample.Test.dll
