language: csharp
solution: Sample.Test.sln
install:
  - nuget restore Sample.Test.sln
  - nuget install NUnit.Runners -Version 2.6.4 -OutputDirectory testrunner
script:
  - xbuild /p:Configuration=Release Sample.Test.sln
  - mono ./testrunner/NUnit.Runners.2.6.4/tools/nunit-console.exe ./Sample.Test/bin/Release/Sample.Test.dll
notifications:
  email:
    - tuankiet234@gmail.com.com
    - huynhhuyphong196@gmail.com
	- ndphuocan.18@gmail.com
	- khanhduyluu@gmail.com
  slack:
	on_success: always
	on_failure: always
